services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
version: '3'
