"""empty message

Revision ID: ca90ae9dacb5
Revises: f84b042e0ff3
Create Date: 2020-05-30 20:04:18.058075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca90ae9dacb5'
down_revision = 'f84b042e0ff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'dislikes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('dislikes', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
