"""added columns for likes and dislikes

Revision ID: f84b042e0ff3
Revises: 
Create Date: 2020-05-30 14:36:50.994633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f84b042e0ff3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('dislikes', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('likes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'likes')
    op.drop_column('posts', 'dislikes')
    # ### end Alembic commands ###
